# Generated by Django 2.0.7 on 2018-07-22 02:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('metro_code', models.CharField(max_length=3)),
                ('country_code', models.CharField(max_length=2)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('nw_bound', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('se_bound', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
