# Generated by Django 2.0.7 on 2018-07-22 02:09

import json
from django.db import migrations
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point, GEOSGeometry


def load_metro_areas(apps, schema_editor):
    Metro = apps.get_model('rom', 'Metro')

    with open('rom/fixtures/metro_data.json') as json_file:
        data = json.load(json_file)

        for d in data:
            try:
                metro = Metro(
                    name = d["name"],
                    metro_code = d["metro_code"],
                    country_code = d["country_code"],
                    centroid = GEOSGeometry('POINT(%s %s)' %(d["centroid"]["longitude"],d["centroid"]["latitude"])),
                    nw_bound = GEOSGeometry('POINT(%s %s)' %(d["nw_bound"]["longitude"],d["nw_bound"]["latitude"])),
                    se_bound = GEOSGeometry('POINT(%s %s)' %(d["se_bound"]["longitude"],d["se_bound"]["latitude"])),
                )
                metro.save()
            except:
                print("Could not add metro area %s" %d["name"])
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_metro_areas)
    ]
