# Generated by Django 2.0.7 on 2018-07-22 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0004_auto_20180722_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
                ('image_type', models.CharField(blank=True, max_length=3, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rom.Hotel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
