# Generated by Django 2.0.7 on 2018-07-22 02:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0008_auto_20180722_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_onestop_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('long_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=6, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rom.Operator')),
            ],
        ),
    ]
