# Generated by Django 2.0.7 on 2018-07-22 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0010_auto_20180722_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_onestop_id', models.CharField(max_length=100)),
                ('wk_trips', models.IntegerField(default=0)),
                ('sa_trips', models.IntegerField(default=0)),
                ('su_trips', models.IntegerField(default=0)),
                ('core_trips', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rom.Route')),
            ],
        ),
    ]
