# Generated by Django 2.0.7 on 2018-07-22 02:46

import json
from django.db import migrations
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point, GEOSGeometry

def load_stop_data(apps, schema_editor):
    Stop = apps.get_model('rom', 'Stop')

    with open('rom/fixtures/stop_data.json') as json_file:
        data = json.load(json_file)

    for d in data:
        try:
            stop = Stop(
                stop_onestop_id = d["stop_onestop_id"],
                name = d["name"],
                geom = GEOSGeometry('POINT(%s %s)' %(d["geom"][0], d["geom"][1]))
            )
            stop.save()
        except Exception as e:
            print("%s" %e)


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0013_stop'),
    ]

    operations = [
        migrations.RunPython(load_stop_data)
    ]
