# Generated by Django 2.0.7 on 2018-07-22 02:50

import json
from django.db import migrations
from django.contrib.gis.db import models


def relate_patterns_and_stops(apps, schema_editor):
    Pattern = apps.get_model('rom', 'Pattern')
    Stop = apps.get_model('rom', 'Stop')

    with open('rom/fixtures/pattern_data.json') as json_file:
        data = json.load(json_file)

        for pattern in data:
            try:
                p = Pattern.objects.get(pattern_onestop_id = pattern["pattern_onestop_id"])
                for stop in pattern["stops"]:
                    s = Stop.objects.get(stop_onestop_id = stop)
                    p.stops.add(s)
            except Exception as e:
                print("%s" %e)
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0015_pattern_stops'),
    ]

    operations = [
        migrations.RunPython(relate_patterns_and_stops)
    ]
