# Generated by Django 2.0.7 on 2018-07-22 03:26

import json
from django.db import migrations
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point, GEOSGeometry


def load_arrival_data(apps, schema_editor):
    Arrival = apps.get_model('rom', 'Arrival')
    Metro = apps.get_model('rom', 'Metro')

    with open('rom/fixtures/arrival_data.json') as json_file:
        data = json.load(json_file)

        for d in data:
            try:
                metro = Metro.objects.get(metro_code = d["metro_code"])
                arrival = Arrival(
                    metro = metro,
                    name = d["name"],
                    geom = GEOSGeometry('POINT(%s %s)' %(d["location"]["longitude"],d["location"]["latitude"])),
                )
                arrival.save()
            except Exception as e:
                print("%s" %e)
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0017_arrival'),
    ]

    operations = [
        migrations.RunPython(load_arrival_data)
    ]
