# Generated by Django 2.0.7 on 2018-07-22 03:29

import json
from django.db import migrations
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point, GEOSGeometry


def load_destination_data(apps, schema_editor):
    Destination = apps.get_model('rom', 'Destination')
    Metro = apps.get_model('rom', 'Metro')

    with open('rom/fixtures/destination_data.json') as json_file:
        data = json.load(json_file)

        for d in data["features"]:
            try:
                metro = Metro.objects.get(metro_code = d["properties"]["metro_code"])
                destination = Destination(
                    metro = metro,
                    name = d["properties"]["place"],
                    geom = GEOSGeometry('POINT(%s %s)' %(d["geometry"]["coordinates"][0],d["geometry"]["coordinates"][1])),
                )
                destination.save()
            except Exception as e:
                print("%s" %e)
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0019_destination'),
    ]

    operations = [
        migrations.RunPython(load_destination_data)
    ]
