# Generated by Django 2.0.7 on 2018-07-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0020_auto_20180722_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rom.Hotel')),
                ('qtr_trips', models.IntegerField()),
                ('qtr_freq_trips', models.IntegerField()),
                ('qtr_dest', models.IntegerField()),
                ('qtr_dest_trips', models.IntegerField()),
                ('half_trips', models.IntegerField()),
                ('half_freq_trips', models.IntegerField()),
                ('half_dest', models.IntegerField()),
                ('half_dest_trips', models.IntegerField()),
            ],
        ),
    ]
