# Generated by Django 2.0.7 on 2018-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0022_auto_20180722_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='half_static_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='qtr_static_score',
            field=models.FloatField(default=0),
        ),
    ]
