# Generated by Django 2.0.7 on 2018-07-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0024_auto_20180722_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelArrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('arrival_score', models.FloatField()),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rom.Arrival')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rom.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='arrivals',
            field=models.ManyToManyField(through='rom.HotelArrival', to='rom.Arrival'),
        ),
    ]
