# Generated by Django 2.0.7 on 2018-07-22 19:50

from django.db import migrations
from django.contrib.gis.db import models


def relate_hotels_and_arrivals(apps, schema_editor):
    Hotel = apps.get_model('rom', 'Hotel')
    Arrival = apps.get_model('rom', 'Arrival')
    HotelArrival = apps.get_model('rom', 'HotelArrival')
    Metro = apps.get_model('rom', 'Metro')

    try:
        for metro in Metro.objects.all():
            hotels = Hotel.objects.filter(metro=metro)
            arrivals = Arrival.objects.filter(metro=metro)

            for hotel in hotels:
                for arrival in arrivals:

                    ha = HotelArrival(
                        hotel = hotel,
                        arrival = arrival,
                        distance = arrival.geom.distance(hotel.geom) * 62.1371
                    )
                    ha.save()
    except Exception as e:
        print("%s" %e)
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0026_auto_20180722_1903'),
    ]

    operations = [
        migrations.RunPython(relate_hotels_and_arrivals)
    ]
