# Generated by Django 2.0.7 on 2018-07-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0027_auto_20180722_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelarrival',
            options={'ordering': ['-hotel__score__qtr_static_score', '-qtr_arrival_score']},
        ),
    ]
