# Generated by Django 2.0.7 on 2018-07-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0028_auto_20180723_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='frequent',
            field=models.BooleanField(default=False),
        ),
    ]
