# Generated by Django 2.0.7 on 2018-07-23 20:56

from django.db import migrations
from django.contrib.gis.db import models
from django.db.models import Sum


def load_route_frequency(apps, schema_editor):
    Route = apps.get_model('rom', 'Route')

    try:
        for route in Route.objects.all():
            core_trips = 0
            for pattern in route.pattern_set.all():
                core_trips += pattern.core_trips
            if core_trips >= 114:
                route.frequent = True
                route.save()
    except Exception as e:
        print("%s" %e)
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0029_route_frequent'),
    ]

    operations = [
        migrations.RunPython(load_route_frequency)
    ]
