# Generated by Django 2.0.7 on 2018-07-23 21:02

from django.db import migrations
from django.contrib.gis.db import models


def relate_hotels_and_destinations(apps, schema_editor):
    Hotel = apps.get_model('rom', 'Hotel')
    Destination = apps.get_model('rom', 'Destination')
    HotelDestination = apps.get_model('rom', 'HotelDestination')
    Metro = apps.get_model('rom', 'Metro')

    try:
        for metro in Metro.objects.all():
            hotels = Hotel.objects.filter(metro=metro)
            destinations = Destination.objects.filter(metro=metro)

            for hotel in hotels:
                for destination in destinations:
                    hd = HotelDestination(
                        hotel = hotel,
                        destination = destination,
                        distance = destination.geom.distance(hotel.geom) * 62.1371
                    )
                    hd.save()
    except Exception as e:
        print("%s" %e)
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0031_auto_20180723_2102'),
    ]

    operations = [
        migrations.RunPython(relate_hotels_and_destinations)
    ]
